# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-18 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_auto_20180717_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dda',
            name='ddaestcod',
        ),
        migrations.RemoveField(
            model_name='dda',
            name='ddapaicod',
        ),
        migrations.RemoveField(
            model_name='dda',
            name='ddatzncod',
        ),
        migrations.RemoveField(
            model_name='ddb',
            name='ddbclicod',
        ),
        migrations.RemoveField(
            model_name='ddb',
            name='ddbddacod',
        ),
        migrations.DeleteModel(
            name='Dda',
        ),
        migrations.DeleteModel(
            name='Ddb',
        ),
    ]
