# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0007_dda_ddb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli',
            name='cliestcod',
            field=models.ForeignKey(blank=True, db_column='cliestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
        migrations.AlterField(
            model_name='dda',
            name='ddaestcod',
            field=models.ForeignKey(blank=True, db_column='ddaestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
        migrations.AlterField(
            model_name='del',
            name='delestcod',
            field=models.ForeignKey(blank=True, db_column='delestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
        migrations.AlterField(
            model_name='pob',
            name='pobestcod',
            field=models.ForeignKey(blank=True, db_column='pobestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='proestcod',
            field=models.ForeignKey(blank=True, db_column='proestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
    ]
