# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 17:43
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tms', '0009_auto_20180727_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli',
            fields=[
                ('clicod', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='clicod')),
                ('cliextcod', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='cliextcod')),
                ('clinom', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='clinom')),
                ('clinif', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='clinif')),
                ('clidir', models.CharField(blank=True, max_length=80, verbose_name='clidir')),
                ('clipcp', models.CharField(blank=True, max_length=20, verbose_name='clipcp')),
                ('clipob', models.CharField(blank=True, max_length=80, verbose_name='clipob')),
                ('cliloc', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='pobloc')),
                ('clitlf', models.CharField(blank=True, max_length=20, verbose_name='clitlf')),
                ('clifax', models.CharField(blank=True, max_length=20, verbose_name='clifax')),
                ('clieml', models.EmailField(blank=True, max_length=254, verbose_name='clieml')),
                ('clida1', models.CharField(blank=True, max_length=20, verbose_name='clida1')),
                ('clida2', models.CharField(blank=True, max_length=20, verbose_name='clida2')),
                ('clida3', models.CharField(blank=True, max_length=20, verbose_name='clida3')),
                ('clida4', models.CharField(blank=True, max_length=20, verbose_name='clida4')),
            ],
        ),
        migrations.CreateModel(
            name='Dda',
            fields=[
                ('ddacod', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ddacod')),
                ('ddanom', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ddanom')),
                ('ddadir', models.CharField(blank=True, max_length=80, verbose_name='ddadir')),
                ('ddapcp', models.CharField(blank=True, max_length=20, verbose_name='ddapcp')),
                ('ddapob', models.CharField(blank=True, max_length=80, verbose_name='ddapob')),
                ('ddapol', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='ddapol')),
                ('ddatlf', models.CharField(blank=True, max_length=20, verbose_name='ddatlf')),
                ('ddafax', models.CharField(blank=True, max_length=20, verbose_name='ddafax')),
                ('ddaeml', models.EmailField(blank=True, max_length=254, verbose_name='ddaeml')),
            ],
        ),
        migrations.CreateModel(
            name='Ddb',
            fields=[
                ('ddbcod', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ddbcod')),
                ('ddbextcod', models.CharField(max_length=20, verbose_name='ddbextcod')),
                ('ddbclicod', models.ForeignKey(db_column='ddbclicod', on_delete=django.db.models.deletion.PROTECT, to='tms.Cli')),
                ('ddbddacod', models.ForeignKey(db_column='ddbddacod', on_delete=django.db.models.deletion.PROTECT, to='tms.Dda')),
            ],
        ),
        migrations.CreateModel(
            name='Del',
            fields=[
                ('delcod', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='delcod')),
                ('delnom', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='delnom')),
                ('deldir', models.CharField(blank=True, max_length=80, verbose_name='deldir')),
                ('delpcp', models.CharField(blank=True, max_length=20, verbose_name='delpcp')),
                ('delpob', models.CharField(blank=True, max_length=80, verbose_name='delpob')),
                ('delloc', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='pobloc')),
                ('deltlf', models.CharField(blank=True, max_length=20, verbose_name='deltlf')),
                ('delfax', models.CharField(blank=True, max_length=20, verbose_name='delfax')),
                ('deleml', models.EmailField(blank=True, max_length=254, verbose_name='deleml')),
                ('delkvs', models.IntegerField(default=0, verbose_name='delkvs')),
                ('delbps', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='delbps')),
            ],
        ),
        migrations.CreateModel(
            name='Dem',
            fields=[
                ('demcod', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='demcod')),
                ('dempcp', models.CharField(max_length=20, verbose_name='demnom')),
                ('demdelcod', models.ForeignKey(db_column='demdelcod', on_delete=django.db.models.deletion.PROTECT, to='tms.Del')),
            ],
        ),
        migrations.CreateModel(
            name='Est',
            fields=[
                ('estcod', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='estcod')),
                ('estnom', models.CharField(blank=True, max_length=40, verbose_name='estnom')),
            ],
        ),
        migrations.CreateModel(
            name='Lng',
            fields=[
                ('lngcod', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='lngcod')),
                ('lngnom', models.CharField(blank=True, max_length=40, verbose_name='lngnom')),
                ('lngdef', models.BooleanField(default=False, verbose_name='lngdef')),
                ('lngact', models.BooleanField(default=True, verbose_name='lngact')),
            ],
        ),
        migrations.CreateModel(
            name='Moa',
            fields=[
                ('moacod', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='moacod')),
                ('moanom', models.CharField(blank=True, max_length=40, verbose_name='moanom')),
                ('moadec', models.SmallIntegerField(default=2, verbose_name='moadec')),
            ],
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('mobcod', models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='mobcod')),
                ('mobfec', models.DateField(default=datetime.date(1, 1, 1), verbose_name='mobfec')),
                ('mobrat', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='mobrat')),
                ('mobmoacod', models.ForeignKey(db_column='mobmoacod', on_delete=django.db.models.deletion.PROTECT, to='tms.Moa')),
            ],
        ),
        migrations.CreateModel(
            name='Pai',
            fields=[
                ('paicod', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='paicod')),
                ('painom', models.CharField(blank=True, max_length=40, verbose_name='painom')),
                ('paic3c', models.CharField(blank=True, max_length=3, verbose_name='paic3c')),
                ('painum', models.SmallIntegerField(default=0, verbose_name='painum')),
            ],
        ),
        migrations.CreateModel(
            name='Pob',
            fields=[
                ('pobcod', models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='pobcod')),
                ('pobnom', models.CharField(max_length=80, verbose_name='pobnom')),
                ('pobloc', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='pobloc')),
                ('pobestcod', models.ForeignKey(blank=True, db_column='pobestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est')),
                ('pobpaicod', models.ForeignKey(db_column='pobpaicod', on_delete=django.db.models.deletion.PROTECT, to='tms.Pai')),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('procod', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='procod')),
                ('proextcod', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='proextcod')),
                ('pronom', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='pronom')),
                ('pronif', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='pronif')),
                ('prodir', models.CharField(blank=True, max_length=80, verbose_name='prodir')),
                ('propcp', models.CharField(blank=True, max_length=20, verbose_name='propcp')),
                ('propob', models.CharField(blank=True, max_length=80, verbose_name='propob')),
                ('proloc', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='pobloc')),
                ('protlf', models.CharField(blank=True, max_length=20, verbose_name='protlf')),
                ('profax', models.CharField(blank=True, max_length=20, verbose_name='profax')),
                ('proeml', models.EmailField(blank=True, max_length=254, verbose_name='proeml')),
                ('proda1', models.CharField(blank=True, max_length=20, verbose_name='proda1')),
                ('proda2', models.CharField(blank=True, max_length=20, verbose_name='proda2')),
                ('proda3', models.CharField(blank=True, max_length=20, verbose_name='proda3')),
                ('proda4', models.CharField(blank=True, max_length=20, verbose_name='proda4')),
                ('proestcod', models.ForeignKey(blank=True, db_column='proestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est')),
                ('promoacod', models.ForeignKey(db_column='promoacod', on_delete=django.db.models.deletion.PROTECT, to='tms.Moa')),
                ('propaicod', models.ForeignKey(db_column='propaicod', on_delete=django.db.models.deletion.PROTECT, to='tms.Pai')),
            ],
        ),
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('version', models.BigIntegerField(default=0)),
                ('seccod', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='seccod')),
                ('secval', models.BigIntegerField(default=0, verbose_name='secval')),
                ('secfmt', models.CharField(blank=True, max_length=20, verbose_name='secfmt')),
            ],
        ),
        migrations.CreateModel(
            name='Tce',
            fields=[
                ('tcecod', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='tcecod')),
                ('tcenom', models.CharField(max_length=40, verbose_name='tcenom')),
                ('tcedimlar', models.DecimalField(decimal_places=3, default=0, max_digits=13, verbose_name='tcedimlar')),
                ('tcedimpes', models.DecimalField(decimal_places=3, default=0, max_digits=13, verbose_name='tcedimpes')),
                ('tcefrg', models.BooleanField(default=False, verbose_name='tcefrg')),
                ('tcefrgset', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='tcefrgset')),
                ('tcefrgmin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='tcefrgmin')),
                ('tcefrgmax', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='tcefrgmax')),
                ('tceact', models.BooleanField(default=True, verbose_name='tceact')),
            ],
        ),
        migrations.CreateModel(
            name='Tct',
            fields=[
                ('tctcod', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='tctcod')),
                ('tctnom', models.CharField(max_length=40, verbose_name='tctnom')),
                ('tctact', models.BooleanField(default=True, verbose_name='tctact')),
            ],
        ),
        migrations.CreateModel(
            name='Tzn',
            fields=[
                ('tzncod', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='tzncod')),
                ('tznabr', models.CharField(blank=True, max_length=5, verbose_name='tznabr')),
            ],
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('vincod', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='vincod')),
                ('vinalf', models.CharField(blank=True, max_length=80, verbose_name='vinalf')),
                ('vinnum', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='vinnum')),
                ('vinfec', models.DateField(default=datetime.date(1, 1, 1), verbose_name='vinfec')),
            ],
        ),
        migrations.AddField(
            model_name='tce',
            name='tcetctcod',
            field=models.ForeignKey(db_column='tcetctcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Tct'),
        ),
        migrations.AddField(
            model_name='pro',
            name='protzncod',
            field=models.ForeignKey(db_column='pobtzncod', on_delete=django.db.models.deletion.PROTECT, to='tms.Tzn'),
        ),
        migrations.AddField(
            model_name='pob',
            name='pobtzncod',
            field=models.ForeignKey(db_column='pobtzncod', on_delete=django.db.models.deletion.PROTECT, to='tms.Tzn'),
        ),
        migrations.AddField(
            model_name='est',
            name='estpaicod',
            field=models.ForeignKey(db_column='estpaicod', on_delete=django.db.models.deletion.PROTECT, to='tms.Pai'),
        ),
        migrations.AddField(
            model_name='del',
            name='delestcod',
            field=models.ForeignKey(blank=True, db_column='delestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
        migrations.AddField(
            model_name='del',
            name='delpaicod',
            field=models.ForeignKey(db_column='delpaicod', on_delete=django.db.models.deletion.PROTECT, to='tms.Pai'),
        ),
        migrations.AddField(
            model_name='del',
            name='deltzncod',
            field=models.ForeignKey(db_column='pobtzncod', on_delete=django.db.models.deletion.PROTECT, to='tms.Tzn'),
        ),
        migrations.AddField(
            model_name='dda',
            name='ddaestcod',
            field=models.ForeignKey(blank=True, db_column='ddaestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
        migrations.AddField(
            model_name='dda',
            name='ddapaicod',
            field=models.ForeignKey(db_column='ddapaicod', on_delete=django.db.models.deletion.PROTECT, to='tms.Pai'),
        ),
        migrations.AddField(
            model_name='dda',
            name='ddatzncod',
            field=models.ForeignKey(db_column='pobtzncod', on_delete=django.db.models.deletion.PROTECT, to='tms.Tzn'),
        ),
        migrations.AddField(
            model_name='cli',
            name='cliestcod',
            field=models.ForeignKey(blank=True, db_column='cliestcod', null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Est'),
        ),
        migrations.AddField(
            model_name='cli',
            name='climoacod',
            field=models.ForeignKey(db_column='climoacod', on_delete=django.db.models.deletion.PROTECT, to='tms.Moa'),
        ),
        migrations.AddField(
            model_name='cli',
            name='clipaicod',
            field=models.ForeignKey(db_column='clipaicod', on_delete=django.db.models.deletion.PROTECT, to='tms.Pai'),
        ),
        migrations.AddField(
            model_name='cli',
            name='clitzncod',
            field=models.ForeignKey(db_column='pobtzncod', on_delete=django.db.models.deletion.PROTECT, to='tms.Tzn'),
        ),
    ]
